"""
JSONL Loader

Loads chunked documents generated by Team A.
"""

import json
from pathlib import Path
from typing import Dict, List


class JSONLoader:
    """
    Utility class for loading JSONL files.
    """

    @staticmethod
    def load(file_path: str) -> List[Dict]:
        """
        Load all records from a JSONL file.

        Args:
            file_path (str): Path to the JSONL file.

        Returns:
            List[Dict]: List of loaded documents.
        """

        path = Path(file_path)

        if not path.exists():
            raise FileNotFoundError(f"JSONL file not found: {file_path}")

        documents = []

        with path.open("r", encoding="utf-8") as file:
            for line in file:

                line = line.strip()

                if not line:
                    continue

                documents.append(json.loads(line))

        return documents

    @staticmethod
    def total_chunks(documents: List[Dict]) -> int:
        """
        Returns total number of chunks.

        Args:
            documents (List[Dict])

        Returns:
            int
        """
        return len(documents)